name = "my-tube"
account_id = "182788b23836a15ba32a69d616ba1db1"
compatibility_date = "2025-01-01"
pages_build_output_dir = ".output"

[[kv_namespaces]]
binding = "mytube"
id = "ff020848600b4885998102246695f1b9"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "mytube"
database_id = "fe0021df-707c-413a-b6bd-8df1e06bdfb2"

[vars]
ASTRO_DB_REMOTE_URL = "https://YOUR_D1_PROJECT.d1.database.dev"
ASTRO_DB_APP_TOKEN = "YOUR_LIBSQL_APP_TOKEN"
PUBLIC_YOUTUBE_CLIENT_ID = "664367767470-omhd95q0gteo48n4pogsmrjhn24pq31b.apps.googleusercontent.com"
PUBLIC_YOUTUBE_REDIRECT_URI = "http://localhost:4173/auth/youtube/callback"
